language: c

python:
  - "2.7"

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=lua5.3
    # - LUA=luajit

branches:
  only:
    - master

before_install:
  - sudo pip install autobahntestsuite
  - bash .travis/setup_lua.sh
  - bash .travis/setup_uv.sh
  - sudo luarocks install luacov-coveralls
  # lua-websockets deps
  - sudo luarocks install struct
  - sudo luarocks install luasocket
  - if [ "$LUA" == "lua5.1" ]; then
      sudo luarocks install bit32;
    fi
  - if [ "$LUA" == "lua5.3" ]; then
      sudo luarocks install bit32;
    fi
  # lua-websockets
  # - git clone https://github.com/moteus/lua-websockets.git -b fix-lua52-compat
  # - cd lua-websockets
  # - sudo luarocks make rockspecs/lua-websockets-scm-1.rockspec --deps-mode=none
  # - cd $TRAVIS_BUILD_DIR
  - sudo luarocks install lua-websockets-core --server=http://rocks.moonscript.org/dev --deps-mode=none
  - sudo luarocks install lluv --server=http://rocks.moonscript.org/dev UV_DIR=$TRAVIS_BUILD_DIR/libuv
  # lua-openssl
  - git clone --depth=1 --recursive https://github.com/zhaozg/lua-openssl.git
  - cd lua-openssl
  - sudo luarocks make rockspecs/openssl-scm-1.rockspec
  - cd $TRAVIS_BUILD_DIR
  - sudo luarocks install lluv-ssl --server=http://rocks.moonscript.org/dev

install:
  - sudo luarocks make rockspecs/lluv-websocket-scm-0.rockspec --deps-mode=none
  - sudo luarocks make rockspecs/lua-websockets-lluv-scm-0.rockspec --deps-mode=none

script: 
  - cd test
  - lua test.lua
  - wstest -m fuzzingserver &
  - sleep 10
  - lua -lluacov ./autobahn_client_test.lua ws://127.0.0.1:9001
  - lua -lluacov ./autobahn_wclient_test.lua ws://127.0.0.1:9001
  - killall wstest
  - wstest -m fuzzingserver -s fuzzingserver_wss.json &
  - sleep 10
  - lua -lluacov ./autobahn_client_test.lua wss://127.0.0.1:9001
  - killall wstest
  - lua -lluacov ./autobahn_server_test.lua ws://127.0.0.1:9002
  - lua -lluacov ./autobahn_server_test.lua wss://127.0.0.1:9002
  - lua -lluacov ./autobahn_wserver_test.lua ws://127.0.0.1:9002

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
