language: c

python:
  - "2.7"

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  # install Lua
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

  # lua-lluv-websocket debps
  - luarocks show lluv-ssl  || bash .travis/setup_uv.sh
  - luarocks show lluv-ssl  || bash .travis/setup_openssl.sh
  # bug in lluv 0.1.3 and in lluv-ssl 0.1.0
  - luarocks show lluv      || luarocks install lluv     --server=http://luarocks.org/dev UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks show lluv-ssl  || luarocks install lluv-ssl --server=http://luarocks.org/dev
  - luarocks show basexx    || luarocks install basexx
  # - luarocks show lbase64   || luarocks install lbase64
  # - luarocks show luacrypto || luarocks install luacrypto
  - if [ "$LUA" == "lua 5.1" ]; then
      luarocks show bit32 || luarocks install bit32;
    fi
  - luarocks show lua-websockets-core || luarocks install lua-websockets-core --server=http://luarocks.org/dev --deps-mode=none

install:
  - luarocks make rockspecs/lluv-websocket-scm-0.rockspec --deps-mode=none
  - luarocks make rockspecs/lua-websockets-lluv-scm-0.rockspec --deps-mode=none

before_script:
  - pip install --user autobahntestsuite
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
  - luarocks show lua-cjson || luarocks install lua-cjson

script: 
  - cd test
  - lua test.lua
  - wstest -m fuzzingserver &
  - sleep 10
  - lua -lluacov ./autobahn_client_test.lua ws://127.0.0.1:9001
  - lua -lluacov ./autobahn_wclient_test.lua ws://127.0.0.1:9001
  - lua -lluacov ./autobahn_co_client_test.lua ws://127.0.0.1:9001
  - killall wstest
  - wstest -m fuzzingserver -s fuzzingserver_wss.json &
  - sleep 10
  - lua -lluacov ./autobahn_client_test.lua wss://127.0.0.1:9001
  - lua -lluacov ./autobahn_wclient_test.lua wss://127.0.0.1:9001
  - lua -lluacov ./autobahn_co_client_test.lua wss://127.0.0.1:9001
  - killall wstest
  - lua -lluacov ./autobahn_server_test.lua ws://127.0.0.1:9002
  - lua -lluacov ./autobahn_server_test.lua wss://127.0.0.1:9002
  - lua -lluacov ./autobahn_wserver_test.lua ws://127.0.0.1:9002
  - lua -lluacov ./autobahn_wserver_test.lua wss://127.0.0.1:9002
  - lua -lluacov ./autobahn_co_server_test.lua ws://127.0.0.1:9002
  - lua -lluacov ./autobahn_co_server_test.lua wss://127.0.0.1:9002

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
